#!/bin/bash
nospaces=`echo $1 | gsed "s/ //g"`
lowercase=`echo $nospaces | gsed "s/.*/\L\0/"`
find . -type f | grep -v "^\.\/\.git" | xargs gsed -i "s/georgecanning/$lowercase/g"
find . -type d -name "georgecanning" | grep -v "^\.\/\.git\/" | while read directory
do
  to=`echo $directory | gsed "s/georgecanning/$lowercase/g"`
  mv $directory $to
  git add $to
done
rm rename
git commit -a -m "Renamed project to $1"
